import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://testcellma.com/cellmaUser/login');
  await page.getByTestId('Username').click();
  await page.getByTestId('Username').fill('release.manoj');
  await page.getByTestId('Password').click();
  await page.getByTestId('Password').fill('Manoj@2025');
  await page.getByTestId('Login').click();
  await page.getByTestId('Patients').click();
  await page.getByTestId('Given Name').click();
  await page.getByTestId('Barcode').click();
  await page.getByTestId('Barcode').fill('89266');
  await page.getByTestId('Search').click();
  await page.getByRole('gridcell', { name: '9762713710' }).click();
  await page.getByTestId('Yes').click();
  await page.getByTestId('Confirm Existing Details').click();
  await page.getByLabel('cancelIcon').click();
  await page.getByTestId('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC0AAAAtCAYAAAA6GuKaAAAACXBIWXMAAAsSAAALEgHS3X78AAABgElEQVRYhWP8//8/w1ADTEPOxaOOpiNgIcUqg5brWa8+/5lKqfPYWBj/s7Mwnf3842/os07dB6TqJykjSpVf/t/oK8mgLcVJqj1gsOrMe4Yrz74zpNqIMMw+8obh7uuf/3/++R/7rFN3KUkGgRxNLJYsu/T/6N0v/8kFPbte/A+acReuO3/l4//yVZf/SpZdEiDFHQOappt8JRnYWRhBbphGir4BdTQfJzODpzY/gxA3iy8p+kjKiNQAx+99BeUNVMdzMLMNWkeDMqClMg+K2NVn3xnqNz8fvI4GJQcrJW6KzRmtxukFRh1NLzD8G0zYwIYN6xmePXuKV01WVg6l1qAAih1tamrG8OPHd6o6ihCg2NHS0tI0dyQ6GE3TxAIpKWmGgIDAgXM0OWmag4O8TgQMjKZpeoHRNE0sGE3TQwWMpmliwWiaHipg1NH0AqOOphcYdTS9AMnlNGjAkJqAHPNIcrQYL0t2/ebnFM+5YDOXFPWjk5/0AqOOpgtgYGAAABoQ/a/7ruwcAAAAAElFTkSuQmCC').click();
  await page.getByTestId('Add Documents').click();
  await page.getByTestId('documentCategory').getByPlaceholder('Please Select').click();
  await page.getByRole('option', { name: 'Investigation' }).click();
  await page.getByTestId('documentSubcategory').getByPlaceholder('Please Select').click();
  await page.getByRole('option', { name: 'Blood Report' }).click();
  await page.getByTestId('specialty').getByPlaceholder('Please Select').click();
  await page.getByRole('option', { name: 'Cardiology' }).click();
  await page.getByTestId('From').click();
  await page.getByTestId('From').fill('TestA');
  await page.getByTestId('To').click();
  await page.getByTestId('To').fill('TestB');
  await page.locator('div').filter({ hasText: /^Sent Date$/ }).getByLabel('Choose date').click();
  await page.getByRole('gridcell', { name: '1', exact: true }).click();
  await page.getByLabel('Choose date', { exact: true }).click();
  await page.getByRole('gridcell', { name: '13' }).click();
  await page.getByTestId('displayName').getByPlaceholder('Please Select').click();
  await page.getByRole('option', { name: 'Blood Report' }).click();
  await page.getByRole('checkbox', { name: 'Private' }).check();
  await page.getByRole('checkbox', { name: 'Private' }).uncheck();
  await page.getByTestId('Description').click();
  await page.getByTestId('Description').fill('for testing');
  await page.getByTestId('Choose File(s)').click();
  await page.getByTestId('Choose File(s)').setInputFiles('User_1.png');
  await page.getByTestId('Upload').click();
  await page.getByLabel('expandRowIcon').click();
  await page.getByLabel('allDocumentsCollapsibleTable').getByTestId('View').click();
});