import { test, expect } from '@playwright/test';
 
test('test', async ({ page }) => {
  await page.goto('https://cellma4testing.riomed.com/cellmaUser/login');
  await page.getByTestId('Username').click();
  await page.getByTestId('Username').fill('saurabh.auto');
  await page.getByTestId('Password').click();
  await page.getByTestId('Password').fill('Saurabh@2025');
  await page.getByTestId('Login').click();
  await page.getByTestId('Patients').click();
  await page.getByTestId('Barcode').click();
  await page.getByTestId('Barcode').fill('788648');
  await page.getByLabel('Search', { exact: true }).click();
  await page.getByTestId('Select').click();
  await page.getByTestId('Confirm Existing Details').click();
  await page.getByTestId('contactReason').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Assessments' }).click();
  await page.getByTestId('Add Contact').click();
  await page.waitForTimeout(2000)
  await page.getByPlaceholder('Please Select').click();
  await page.getByRole('option', { name: 'Documents' }).click();
  //await page.getByTestId('Add Documents').click();
  await page.waitForTimeout(2000)
  await page.getByTestId('Add Documents').click();
  await page.getByTestId('documentCategory').getByPlaceholder('Please Select').click();
  await page.getByRole('option', { name: 'Investigation' }).click();
  await page.getByTestId('documentSubcategory').getByPlaceholder('Please Select').click();
  await page.getByRole('option', { name: 'Blood Report' }).click();
  await page.getByTestId('specialty').getByPlaceholder('Please Select').click();
  await page.getByRole('option', { name: 'Cardiology' }).click();
  await page.getByTestId('From').click();
  await page.getByTestId('From').fill('Test');
  await page.getByTestId('To').click();
  await page.getByTestId('To').fill('Riomed');
  await page.getByTestId('Sent Date').click();
  await page.getByTestId('Sent Date').fill('01/01/2025');
  await page.getByTestId('Received Date').click();
  await page.getByTestId('Received Date').fill('01/06/2025');
  await page.getByTestId('displayName').getByLabel('Open').click();
  await page.getByRole('option', { name: 'Blood Report' }).click();
  await page.getByRole('checkbox', { name: 'Private' }).check();
  await page.getByRole('checkbox', { name: 'Private' }).uncheck();
  await page.getByRole('checkbox', { name: 'Share on Portal' }).check();
  await page.getByRole('checkbox', { name: 'Share with Patient Interested' }).check();
  await page.getByTestId('Description').click();
  await page.getByTestId('Description').fill('Test document');
  await page.getByTestId('Choose File(s)').click();
  await page.pause()
  //await page.getByTestId('Choose File(s)').setInputFiles('sampleunsecuredpdf.pdf');
  await page.getByTestId('Upload').click();
  await page.getByRole('cell', { name: 'expandRowIcon' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByLabel('allDocumentsCollapsibleTable').getByTestId('View').click();
  await page.pause()
 // const page1 = await page1Promise;
  await page.getByLabel('edit', { exact: true }).click();
  await page.getByTestId('From').click();
  await page.getByTestId('From').fill('Testone');
  await page.getByTestId('To').click();
  await page.getByTestId('To').fill('Riomedtwo');
  await page.getByTestId('Save').click();
  await page.getByLabel('highlightNo').click();
  await page.getByLabel('highlightNo').click();
  await page.getByLabel('highlightNo').click();
  await page.getByRole('cell', { name: 'expandRowIcon' }).click();
  await page.getByLabel('edit', { exact: true }).click();
  await page.getByTestId('Delete').click();
  await page.getByTestId('Ok').click();
  await page.getByTestId('Reason').click();
  await page.getByTestId('Reason').fill('Not required');
  await page.getByTestId('CommonCellmaPopup').getByTestId('Save').click();
  await page.getByRole('tab', { name: 'Migrated' }).click();
  await page.getByRole('tab', { name: 'Deleted' }).click();
  await page.getByTestId('archived').click();
  await page.getByLabel('cancelIcon').click();
  await page.getByTestId('tasks').click();
  await page.getByTestId('allDocuments').click();
  await page.getByLabel('profileIcon').click();
  await page.getByText('Logout').click();
});