import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://testcellma.com/cellmaUser/login');
  await page.getByTestId('Username').click();
  await page.getByTestId('Username').fill('release.manoj');
  await page.getByTestId('Password').click();
  await page.getByTestId('Password').fill('Manoj@2025');
  await page.getByTestId('Login').click();
  await page.getByTestId('todaysAppointments').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('myAlerts').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('myAlerts').getByLabel('cellmaAccordionIcon').click();
  await page.getByLabel('expandRowIconundefined').first().click();
  await page.getByLabel('expandRowIconundefined').first().click();
  await page.getByTestId('myAlerts').getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'messages My Messages' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('row', { name: 'expandRowIconManish Patil Manish Patil User 02/05/2024 09:15 am 2 Manish' }).getByLabel('expandRowIconManish Patil').click();
  await page.getByRole('row', { name: 'expandRowIconManish Patil Manish Patil User 02/05/2024 09:15 am 2 Manish' }).getByLabel('expandRowIconManish Patil').click();
  await page.getByRole('button', { name: 'messages My Messages' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('myTasks').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('myTasks').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('Worklist').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('Worklist').getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'myCommunication Communication' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'myCommunication Communication' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'CaseLoad Image Avatar My' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'CaseLoad Image Avatar My' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('Expand All').click();
  await page.getByTestId('Close All').click();
  await page.getByLabel('serviceAppointment', { exact: true }).click();
  await page.getByLabel('Back Button').click();
  await page.getByLabel('serviceAlert', { exact: true }).click();
  await page.getByLabel('Back Button').click();
  await page.getByLabel('serviceMessages').click();
  await page.getByLabel('cancelIcon').click();
  await page.getByLabel('serviceTasks').click();
  await page.getByTestId('myDetails').click();
  await page.getByLabel('worklist', { exact: true }).click();
  await page.getByLabel('Back Button').click();
  await page.getByLabel('communication', { exact: true }).click();
  await page.getByLabel('Back Button').click();
  await page.getByLabel('myCaseLoad').click();
  await page.getByLabel('Back Button').click();
  await page.getByLabel('profileIcon').click();
  await page.getByText('Logout').click();
});